### ISSUE TITLE
Will linux-pbp get updates?

### ISSUE THREAD

**Issue by shlyakpavel** [bengtfredh/pinebook-pro-copr#3]
Hello!
Did you decide to stick with linux-manjaro without updating linux-pbp?
Patches for 5.17.x are already available https://gitlab.manjaro.org/manjaro-arm/packages/core/linux
Should I switch to linux-manjaro from linux-pbp to get new kernel versions?

**Comment by bengtfredh** [comment]
Just been busy with my day job.

**Comment by shlyakpavel** [comment]
Ok. Thank you for your work! I really appreciate running Fedora on my pine64 daily driver :)
